# Generated by Django 4.2.9 on 2024-01-24 03:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_talentaccount_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('message', models.TextField(max_length=500)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='talentaccount',
            name='pp_cropping',
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='contact_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.contactinfo'),
        ),
    ]
