# Generated by Django 4.2.9 on 2024-01-25 01:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_contactinfo_remove_talentaccount_pp_cropping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='website',
        ),
        migrations.RemoveField(
            model_name='talentaccount',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='talentaccount',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='contact_email',
            field=models.EmailField(max_length=70, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='instagram',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
