# Generated by Django 4.2.9 on 2024-01-25 01:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_contactinfo_email_remove_contactinfo_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentaccount',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='talentaccount',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='talentaccount',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='talentaccount',
            name='website',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=70, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='website',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='contact_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.contactinfo'),
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
