# Generated by Django 4.2.9 on 2024-01-27 23:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_contactinfo_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentaccount',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='contact_email',
            field=models.EmailField(max_length=70, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='contact_instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='talentaccount',
            name='contact_website',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
