# Generated by Django 4.2.9 on 2024-01-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_talentaccount_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.png', null=True, upload_to='profile_pictures'),
        ),
    ]
